### PR TITLE
translation: 产出 -> 产物，感觉用产物会好些？

### PR DESCRIPTION
**Pull request by jacob-lcs**

### CODE REVIEW

**Comment by frehner** [comment]
@SyMind thoughts on this?

**Comment by SyMind** [comment]
@jacob-lcs 

我觉得『产出』更好一些，首先『产出』和『产物』两个词的意思分别如下：

> 产出是指生产过程中创造的各种有用的物品或劳务，它们可以用于消费或用于进一步生产。产出主要用于消费或进一步加工生产的各种有用的物品和服务。

> 产物是在某种条件下产生的事物或结果。按照产物的产生原因和过程，可分为天然产物和人工产物。产物是多种条件和因素下作用的结果。产物对于人类来说，可能是有利的东西，可能是有害的事物。它们以是否满足人们的需要为前提。

显然产出更加清晰地说明这是人工产出，且可以用于进一步的开发，概念上更加和一个 NPM 输出的内容相吻合。

**Comment by SyMind** [comment]
@frehner

I think the current "产出" is better. In Chinese, the meanings of "产出" and "产物" are as follows:

> "产出" is refers to all kinds of useful goods or services created in the production process, which can be used for consumption or further production. The output is mainly used for consumption or further processing and production of various useful goods and services.

> "产物" is a thing or result produced under certain conditions. According to the causes and processes of products, they can be divided into natural products and artificial products. The product is the result of a variety of conditions and factors. Products may be beneficial or harmful to human beings. They are based on meeting people's needs.

Obviously, the "产出" more clearly indicates that it is an artifact and can be used for further development.

**Comment by jacob-lcs** [comment]
现在来看使用打包产物的会更多些，很少看到有打包产出的，当然只是个人建议～

**Comment by frehner** [comment]
Thanks, I appreciate the two of you working this out. ❤️

**Pull request closed without merging**
