### PR TITLE
sync content change

### PR DESCRIPTION
**Pull request by SyMind**

### CODE REVIEW

**Comment by frehner** [comment]
This is looking great! Let me know when you feel like it's done!

**Comment by frehner** [comment]
Do you want to add a section at the end that credits you for the translation?

**Comment by SyMind** [comment]
it have already done.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Anthony Frehner ***@***.***>
发送时间: Wednesday, September 14, 2022 10:08:55 AM
收件人: frehner/modern-guide-to-packaging-js-library ***@***.***>
抄送: Cong-Cong Pan ***@***.***>; Author ***@***.***>
主题: Re: [frehner/modern-guide-to-packaging-js-library] sync content change (PR #21)


This is looking great! Let me know when you feel like it's done!

―

**Comment by SyMind** [comment]
> Do you want to add a section at the end that credits you for the translation?

It's my pleasure. I have already add.

**Review by frehner — APPROVED** [review]

**Comment by frehner** [comment]
Thank you!

**Pull request merged**
